server:
  port: 10000
logging:
  level:
    root: info
  file:
    path: ./
    name: info.log

sunshine-hook:
  config:
    event-queue-config:
      max-size: 100
      consume-delay: 10
    hook-event-config:
      branch-filter: master
      event-filter: push
      script-path: ./
      secret-key: 123456