server:
  port: 10000
logging:
  level:
    root: info
  file:
    path: ./
    name: info.log

sunshine-hook:
  config:
    max-size: 100
    consume-delay: 10
    branch-filter: master
    event-filter: push
    script-path: ./trigger.sh
    secret-key: 123456